// +build ignore

// This program generates emojis.go. It can be invoked by running
// go generate
package main

import (
	"html/template"

	"github.com/Robindiddams/emojidict/scraper"
)

func main() {
	// rejectex := regexp.MustCompile("^[#0]")
	// acceptex := regexp.MustCompile("(.*)\\s+;\\sfully-qualified\\s+#\\s([^\\s]*)\\s(.*)")
	// if !rejectex.MatchString(line) && acceptex.MatchString(line) {
	// 	matches := acceptex.FindStringSubmatch(line)
	// 	return &Character{
	// 		Value:       matches[2],
	// 		Description: strings.TrimSpace(matches[3]),
	// 		Hex:         strings.TrimSpace(matches[1]),
	// 	}
	// }
	scraper.GetLatestEmojiFile()
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
// using data from
// {{ .URL }}
package project

var Contributors = []string{
{{- range .Carls }}
	{{ printf "%q" . }},
{{- end }}
}
`))
